import { Expense, TripExpense } from "../../../domain/expense";

export function createTestableExpense(): Expense {
  return new TripExpense(
    Math.floor(Math.random() * 1000) + 1,
    Math.floor(Math.random() * 1000) + 1,
    new Date(),
    new Date(),
    "autogenerated",
    Math.floor(Math.random() * 1000) + 1
  );
}
